# -*- coding: utf-8 -*-
"""
Run the real 1991 TALKHUN0.COM under Unicorn and capture the PCF-8200 frames
it sends to the BraiLab adapter.

No memory snapshot is needed.  TALKHUN0 is a plain .COM that installs itself as
a TSR hooking INT 14h, so we build a PSP, load the image at seg:0x100, run its
own installer with DOS shimmed, and stop at the AX=3100 (TSR) call.  What is
left in emulator memory *is* the resident engine -- generated by the original
installer rather than captured from a running DOS.

Speech API, recovered from the handler at 0x1168:
    INT 14h, DL=3 (COM4), AH=0        -> reset settings
    INT 14h, DL=3,        AH=1, AL=c  -> feed one character to the ESC parser
    INT 14h, DL=3,        AH=3        -> status, returns AX=0x30
Any other DL chains to the saved original vector.

The engine is line buffered: characters accumulate until an intonation-unit
delimiter (. , ; : ? !) arrives, and only then are frames emitted.

The adapter link is a 2-wire bit-bang over the printer port:
    0x1e40  out base+0 <- (clock<<1)|data ; out base+2 <- same ^ 2
    0x1e2b  one bit from CF, clock low/high/low
    0x1df8  8 data bits MSB first, then a stop bit
    0x1df0  preamble + a 0x20 frame marker      0x1e1c  postamble
A transaction is  preamble, 0x20 marker, payload, postamble.  Five payload
bytes are a speech frame; two are a control write (0x00 then the command byte).

The printer STATUS port at base+1 drives the ready poll at 0x1dc4, which returns
CF=0 when bit 4 is clear ("ready"), and CF=1 when bit 4 is set with bit 5 clear.
The polarity is not uniform across callers: the utterance-start control write at
0x1d2c proceeds only on CF=1, while every later poll wants CF=0.  Physically
that is an adapter whose busy line rests high and drops once it has been
addressed, so the model here reports busy for the first poll of an utterance and
ready from then on.  Getting this wrong is silent -- with "always ready" the
engine still emits all its speech frames, but the start control write carrying
furcsa and tempo is skipped entirely.
"""

import os
import struct

from unicorn import (
    Uc, UcError, UC_ARCH_X86, UC_MODE_16, UC_PROT_ALL,
    UC_HOOK_INSN, UC_HOOK_INTR, UC_HOOK_BLOCK, UC_HOOK_CODE,
)
from unicorn.x86_const import (
    UC_X86_INS_IN, UC_X86_INS_OUT,
    UC_X86_REG_AX, UC_X86_REG_AL, UC_X86_REG_BX, UC_X86_REG_CX,
    UC_X86_REG_DX, UC_X86_REG_SI, UC_X86_REG_DI, UC_X86_REG_BP,
    UC_X86_REG_SP, UC_X86_REG_CS, UC_X86_REG_DS, UC_X86_REG_ES,
    UC_X86_REG_SS, UC_X86_REG_IP, UC_X86_REG_EFLAGS,
)

MEM_SIZE = 0x110000
#: The installer's already-resident check walks every segment below CS, so a
#: modest load segment keeps that scan short.
PROG_SEG = 0x0800
SENTINEL_SEG = 0x9000
SENTINEL = SENTINEL_SEG * 16
STACK_TOP = 0xFFFE

LPT_BASE = 0x378
BIOS_LPT1 = 0x408                       # 0040:0008
BIOS_TICK = 0x46C                       # 0040:006C

INT14 = 0x14
COM4 = 3

#: Printer status values the poll at 0x1dc4 distinguishes.
STATUS_BUSY = 0x10                      # bit4 set, bit5 clear -> CF=1 at once
STATUS_READY = 0x00                     # bit4 clear            -> CF=0

MAX_INSNS = 20_000_000

#: Code addresses in the 1991 image.  Hooking the byte shifter gives the
#: transmitted stream directly.
V1_SEND_BYTE = 0x1DF8
V1_PREAMBLE = 0x1DF0
V1_POSTAMBLE = 0x1E1C
#: Utterance-start control write; entering it arms the busy-at-rest handshake.
V1_CTRL_WRITE = 0x1D2C

#: Any of these flushes the buffered line (HALLGASD.MEG's intonation units).
DELIMITERS = '.,;:?!'


class TalkhunError(RuntimeError):
    pass


class Talkhun:
    """The 1991 BraiLab talker, resident inside Python."""

    def __init__(self, com_path):
        with open(com_path, 'rb') as f:
            self.image = f.read()
        self._busy = False
        self.banners = []
        self.events = []                # ('pre'|'byte'|'post', value)
        self.int14 = None
        self.exited = None
        self._ticks = 0
        self._build()

    # -- construction ------------------------------------------------------
    def _build(self):
        uc = Uc(UC_ARCH_X86, UC_MODE_16)
        uc.mem_map(0, MEM_SIZE, UC_PROT_ALL)
        self.uc = uc

        uc.mem_write(BIOS_LPT1, struct.pack('<H', LPT_BASE))
        uc.mem_write(BIOS_TICK, struct.pack('<I', 0))

        # A minimal PSP: int 20h at :0000, empty command tail at :0080.
        psp = bytearray(0x100)
        psp[0:2] = b'\xcd\x20'
        psp[0x2C:0x2E] = struct.pack('<H', 0)
        uc.mem_write(PROG_SEG * 16, bytes(psp))
        uc.mem_write(PROG_SEG * 16 + 0x100, self.image)

        uc.hook_add(UC_HOOK_INSN, self._on_in, None, 1, 0, UC_X86_INS_IN)
        uc.hook_add(UC_HOOK_INSN, self._on_out, None, 1, 0, UC_X86_INS_OUT)
        uc.hook_add(UC_HOOK_INTR, self._on_intr)
        uc.hook_add(UC_HOOK_BLOCK, self._on_block)
        for addr in (V1_SEND_BYTE, V1_PREAMBLE, V1_POSTAMBLE):
            lin = PROG_SEG * 16 + addr
            uc.hook_add(UC_HOOK_CODE, self._on_send, None, lin, lin)
        lin = PROG_SEG * 16 + V1_CTRL_WRITE
        uc.hook_add(UC_HOOK_CODE, self._on_ctrl_write, None, lin, lin)

    # -- hooks -------------------------------------------------------------
    def _on_ctrl_write(self, uc, address, size, user):
        self._busy = True               # adapter looks busy until addressed

    def _on_in(self, uc, port, size, user):
        if port != LPT_BASE + 1:
            return 0xFF
        if self._busy:
            self._busy = False
            return STATUS_BUSY
        return STATUS_READY

    def _on_out(self, uc, port, size, value, user):
        pass                            # the code hook carries the byte stream

    def _on_block(self, uc, address, size, user):
        # The ready poll times out against the BIOS tick at 0040:006C; if that
        # never advances, a poll that is waiting can never give up.
        self._ticks += 1
        if self._ticks % 512 == 0:
            uc.mem_write(BIOS_TICK,
                         struct.pack('<I', (self._ticks // 512) & 0xFFFFFFFF))

    def _on_send(self, uc, address, size, user):
        off = address - PROG_SEG * 16
        if off == V1_SEND_BYTE:
            self.events.append(('byte', uc.reg_read(UC_X86_REG_AL)))
        elif off == V1_PREAMBLE:
            self.events.append(('pre', None))
        else:
            self.events.append(('post', None))

    def _on_intr(self, uc, intno, user):
        ax = uc.reg_read(UC_X86_REG_AX)
        ah, al = (ax >> 8) & 0xFF, ax & 0xFF

        def cf_clear():
            uc.reg_write(UC_X86_REG_EFLAGS,
                         uc.reg_read(UC_X86_REG_EFLAGS) & ~0x01)

        if intno == 0x21:
            if ah == 0x09:                          # print $-terminated string
                ds, dx = uc.reg_read(UC_X86_REG_DS), uc.reg_read(UC_X86_REG_DX)
                buf = bytes(uc.mem_read(ds * 16 + dx, 256))
                end = buf.find(b'$')
                self.banners.append(
                    buf[:end if end >= 0 else 0].decode('cp852', 'replace'))
                cf_clear()
            elif ah == 0x35:                        # get interrupt vector
                off, seg = struct.unpack('<HH', uc.mem_read(al * 4, 4))
                uc.reg_write(UC_X86_REG_ES, seg)
                uc.reg_write(UC_X86_REG_BX, off)
                cf_clear()
            elif ah == 0x25:                        # set interrupt vector
                ds, dx = uc.reg_read(UC_X86_REG_DS), uc.reg_read(UC_X86_REG_DX)
                uc.mem_write(al * 4, struct.pack('<HH', dx, ds))
                if al == INT14:
                    self.int14 = (ds, dx)
                cf_clear()
            elif ah == 0x49:                        # free memory block
                cf_clear()
            elif ah == 0x31:                        # TSR -- install complete
                self.exited = 'tsr'
                uc.emu_stop()
            elif ah == 0x4C:
                self.exited = 'exit(%d)' % al
                uc.emu_stop()
            else:
                cf_clear()
        elif intno == 0x20:
            self.exited = 'int20'
            uc.emu_stop()
        elif intno == 0x16:                         # keyboard: never a key
            if ah in (0x01, 0x11):
                uc.reg_write(UC_X86_REG_EFLAGS,
                             uc.reg_read(UC_X86_REG_EFLAGS) | 0x40)
            uc.reg_write(UC_X86_REG_AX, 0)

    # -- running -----------------------------------------------------------
    def _push(self, value):
        uc = self.uc
        sp = (uc.reg_read(UC_X86_REG_SP) - 2) & 0xFFFF
        ss = uc.reg_read(UC_X86_REG_SS)
        uc.mem_write(ss * 16 + sp, struct.pack('<H', value & 0xFFFF))
        uc.reg_write(UC_X86_REG_SP, sp)

    def install(self):
        """Run the .COM installer up to its TSR call.  Returns (seg, off)."""
        uc = self.uc
        for reg in (UC_X86_REG_AX, UC_X86_REG_BX, UC_X86_REG_CX, UC_X86_REG_DX,
                    UC_X86_REG_SI, UC_X86_REG_DI, UC_X86_REG_BP):
            uc.reg_write(reg, 0)
        for reg in (UC_X86_REG_CS, UC_X86_REG_DS, UC_X86_REG_ES, UC_X86_REG_SS):
            uc.reg_write(reg, PROG_SEG)
        uc.reg_write(UC_X86_REG_SP, STACK_TOP)
        self._push(0)                               # DOS's .COM return word
        uc.reg_write(UC_X86_REG_IP, 0x100)
        try:
            uc.emu_start(PROG_SEG * 16 + 0x100, SENTINEL, count=MAX_INSNS)
        except UcError as e:
            raise TalkhunError('install faulted: %s' % e)
        if self.exited != 'tsr':
            raise TalkhunError('installer did not reach TSR (got %r); banners=%r'
                               % (self.exited, self.banners))
        if self.int14 is None:
            raise TalkhunError('installer never hooked INT 14h')
        return self.int14

    def _call_int14(self, ah, al=0, dl=COM4):
        uc = self.uc
        seg, off = self.int14
        uc.reg_write(UC_X86_REG_SS, PROG_SEG)
        uc.reg_write(UC_X86_REG_SP, STACK_TOP)
        uc.reg_write(UC_X86_REG_AX, ((ah & 0xFF) << 8) | (al & 0xFF))
        uc.reg_write(UC_X86_REG_DX, dl & 0xFF)
        uc.reg_write(UC_X86_REG_CS, seg)
        uc.reg_write(UC_X86_REG_IP, off)
        # The handler ends in iret, which pops IP, CS and FLAGS.
        self._push(uc.reg_read(UC_X86_REG_EFLAGS))
        self._push(SENTINEL_SEG)
        self._push(0)
        try:
            uc.emu_start(seg * 16 + off, SENTINEL, count=MAX_INSNS)
        except UcError as e:
            raise TalkhunError('int14 ah=%d faulted: %s' % (ah, e))
        cs, ip = uc.reg_read(UC_X86_REG_CS), uc.reg_read(UC_X86_REG_IP)
        if cs * 16 + ip != SENTINEL:
            raise TalkhunError('int14 ah=%d did not return (cs:ip=%04x:%04x)'
                               % (ah, cs, ip))

    def reset(self):
        """AH=0: settings back to the engine's own defaults."""
        self._call_int14(0)

    def feed(self, text):
        """Push characters through the ESC parser without forcing a flush."""
        if isinstance(text, str):
            text = text.encode('cp852', 'replace')
        for ch in text:
            self._call_int14(1, ch)

    # -- capture -----------------------------------------------------------
    def transactions(self, since=0):
        """Group the event stream into preamble..postamble payloads."""
        groups, cur = [], None
        for kind, val in self.events[since:]:
            if kind == 'pre':
                cur = []
                groups.append(cur)
            elif kind == 'post':
                cur = None
            elif cur is not None:
                cur.append(val)
        return groups

    def capture(self, text):
        """Speak `text` and return the adapter traffic in order.

        Yields ('pitch', byte), ('ctrl', bytes) and ('frame', bytes) items.
        Order matters: text containing several intonation units produces one
        start sequence per unit, each with its own pitch.

        A delimiter is appended when the text has none, since the engine will
        otherwise hold the line in its buffer and emit nothing.
        """
        if not text:
            return []
        if text[-1] not in DELIMITERS:
            text = text + '.'
        mark = len(self.events)
        self.feed(text)
        groups = self.transactions(mark)
        # The driver calls this for every utterance of a session, so drop the
        # events once they have been grouped rather than accumulating forever.
        del self.events[:]

        out, singles = [], 0
        for g in groups:
            if not g or g[0] != 0x20:
                continue
            body = g[1:]
            if len(body) == 5:
                out.append(('frame', body))
            elif len(body) == 2:
                out.append(('ctrl', body))
            elif len(body) == 1:
                # A start sequence sends the settings nibble, then the pitch.
                if singles % 2:
                    out.append(('pitch', body[0]))
                singles += 1
        return out

    def synthesize(self, text):
        """Speak `text` and return (frames, control_writes)."""
        seq = self.capture(text)
        return ([v for k, v in seq if k == 'frame'],
                [v for k, v in seq if k == 'ctrl'])


def load(com_path=None):
    """Build an installed engine ready to synthesize."""
    if com_path is None:
        com_path = os.path.join(os.path.dirname(os.path.dirname(
            os.path.abspath(__file__))), 'BRAILAB-archive', 'TALKHUN0.COM')
    t = Talkhun(com_path)
    t.install()
    t.reset()
    return t
